#' Load embeddings generated by the \link{pkgmatch_embeddings_from_pkgs}
#' function, either for all rOpenSci packages or, if `fns = TRUE`,  all
#' individual functions within those packages.
#'
#' @inheritParams pkgmatch_similar_pkgs
#' @param what One of:
#' \itemize{
#' \item "embeddings" to load pre-generated embeddings;
#' \item "idfs" to load pre-generated Inverse Document Frequency weightings;
#' \item "functions" to load pre-generated frequency tables for text
#' descriptions of function calls; or
#' \item "calls" to load pre-generated frequency tables for actual function
#' calls.
#' }
#' @param fns If `FALSE` (default), load embeddings for all rOpenSci packages;
#' otherwise load (considerably larger dataset of) embeddings for all
#' individual functions.
#' @param raw Only has effect of `what = "calls"`, in which case default of
#' `FALSE` loads single Inverse Document Frequency table to entire corpus;
#' otherwise if `TRUE`, loads raw function call counts for each package in
#' corpus.
#' @return The loaded `data.frame`.
#'
#' @family utils
#' @export
#'
#' @examples
#' \dontrun{
#' embeddings <- pkgmatch_load_data ("embeddings")
#' embeddings_fns <- pkgmatch_load_data ("embeddings", fns = TRUE)
#' idfs <- pkgmatch_load_data ("idfs")
#' idfs_fns <- pkgmatch_load_data ("idfs", fns = TRUE)
#' }
pkgmatch_load_data <- function (what = "embeddings",
                                corpus = "ropensci",
                                fns = FALSE,
                                raw = FALSE) {

    checkmate::assert_character (what, len = 1L)
    checkmate::assert_character (corpus, len = 1L)
    checkmate::assert_logical (fns, len = 1L)
    checkmate::assert_logical (raw, len = 1L)

    m_load_data_internal (what, corpus, fns, raw)
}

pkgmatch_cache_update_interval <- function () {
    dt <- 30

    op <- getOption ("pkgmatch.update_frequency")
    if (!is.null (op)) {
        op <- tryCatch (as.integer (op), error = function (e) NULL)
    }
    if (!is.null (op)) {
        dt <- op
    }
    return (dt)
}

# nocov start

#' Update all locally-cached `pkgmatch` data to latest versions.
#'
#' Locally-cached data used by this package are generally updated every 30
#' days, or according to `options("pkgmatch.update_frequency")` if that is set.
#' This function forces all locally-cached data to be updated, regardless of
#' update frequencies. Remote data are provided on the latest release of GitHub
#' repository at
#' \url{https://github.com/ropensci-review-tools/pkgmatch/releases}.
#'
#' @family utils
#' @export
#'
#' @examples
#' \dontrun{
#' pkgmatch_update_cache ()
#' }
pkgmatch_update_cache <- function () {

    what <- c ("embeddings", "idfs", "functions", "calls")
    corpus <- c ("ropensci", "cran")
    fns <- c (FALSE, TRUE)
    raw <- c (FALSE, TRUE)

    vals <- expand.grid (what = what, corpus = corpus, fns = fns, raw = raw)
    vals$fname <- apply (vals, 1, function (i) {
        get_cache_file_name (
            what = i [1], corpus = i [2], fns = i [3], raw = i [4]
        )
    })
    vals <- vals [-which (duplicated (vals$fname)), ]

    files <- apply (vals, 1, function (i) {
        pkgmatch_dl_data (
            what = i [1], corpus = i [2], fns = i [3], raw = i [4]
        )
    })

    invisible (files)
}
# nocov end

load_data_internal <- function (what, corpus, fns, raw) {
    fname <- get_cache_file_name (what, corpus, fns, raw)

    fname <- fs::path (pkgmatch_cache_path (), fname)
    dl <- !fs::file_exists (fname)
    if (!dl) {
        # Check whether existing file should be updated
        fdate <- as.Date (fs::file_info (fname)$modification_time)
        dt <- difftime (as.Date (Sys.time ()), fdate, units = "days")
        dl <- dt > pkgmatch_cache_update_interval ()
        if (dl) {
            cli::cli_inform (
                "Local data are {dt} days old and will be updated ..."
            )
        }
    }
    if (dl) {
        fns_msg <- ifelse (fns, "functions ", "")
        msg <- "Downloading {what} {fns_msg}data for {corpus} corpus"
        cli::cli_alert_info (msg)
        fname <- pkgmatch_dl_data (
            what = what, corpus = corpus, fns = fns, raw = raw
        )
    }
    readRDS (fname)
}
m_load_data_internal <- memoise::memoise (load_data_internal)

m_list_remote_files <- function () {
    piggyback::pb_list (
        repo = "ropensci-review-tools/pkgmatch",
        tag = RELEASE_TAG
    )
}
list_remote_files <- memoise::memoise (m_list_remote_files)

get_cache_file_name <- function (what, corpus, fns, raw) {

    corpus <- match.arg (tolower (corpus), c ("ropensci", "cran"))
    what <- match.arg (what, c ("embeddings", "idfs", "functions", "calls"))

    if (corpus == "ropensci") {

        fname <- switch (what,
            "embeddings" = ifelse (
                fns, "embeddings-fns.Rds", "embeddings-ropensci.Rds"
            ),
            "idfs" = ifelse (fns, "bm25-ropensci-fns.Rds", "bm25-ropensci.Rds"),
            "functions" = "fn-calls-ropensci.Rds",
            "calls" = ifelse (
                raw, "fn-calls-ropensci.Rds", "idfs-fn-calls-ropensci.Rds"
            )
        )

    } else if (corpus == "cran") {

        fname <- switch (what,
            "embeddings" = "embeddings-cran.Rds",
            "idfs" = "bm25-cran.Rds",
            "functions" = "fn-calls-cran.Rds",
            "calls" = ifelse (
                raw, "fn-calls-cran.Rds", "idfs-fn-calls-cran.Rds"
            )
        )
    }

    return (fname)
}

# nocov start
pkgmatch_dl_data <- function (what = "embeddings", corpus = "ropensci",
                              fns = FALSE, raw = FALSE) {

    fname <- get_cache_file_name (what, corpus, fns, raw)

    url_base <-
        "https://github.com/ropensci-review-tools/pkgmatch/releases/download/"
    version <- "v0.4.0"

    dl_url <- paste0 (url_base, version, "/", fname)

    destfile <- fs::path (pkgmatch_cache_path (), fname)
    curl::curl_download (
        url = dl_url,
        destfile = destfile,
        quiet = opt_is_quiet ()
    )
    return (destfile)
}
# nocov end

pkgmatch_cache_path <- function () {

    cache_dir <- Sys.getenv ("PKGMATCH_CACHE_DIR")

    if (cache_dir == "") { # nocov start
        cache_dir <- fs::path_expand (fs::path (
            rappdirs::user_cache_dir (),
            "R",
            "pkgmatch"
        ))
        if (!fs::dir_exists (cache_dir)) {
            fs::dir_create (cache_dir, recurse = TRUE)
        }
    } # nocov end

    return (cache_dir)
}

send_dl_message <- function (fnames) {

    corpus <- unique (gsub ("^.*\\-|\\.Rds$", "", fnames))
    flist <- fs::dir_ls (pkgmatch_cache_path ())
    extant_files <- any (grepl (corpus, flist))
    if (!extant_files) {
        cli::cli_alert_info ("This function requires data to be downloaded.")
    }

    flist <- fs::path (pkgmatch_cache_path (), fnames)
    flist_dl <- flist [which (!fs::file_exists (flist))]
    flist <- flist [which (fs::file_exists (flist))]

    fdates <- as.Date (fs::file_info (flist)$modification_time)
    dt <- difftime (as.Date (Sys.time ()), fdates, units = "days")
    flist <- flist [which (dt > pkgmatch_cache_update_interval ())]

    flist <- c (flist_dl, flist)
    finfo_count <- length (flist)
    if (finfo_count == 0L) {
        return ()
    }

    finfo <- list_remote_files () |>
        dplyr::filter (file_name %in% basename (flist))
    finfo_size <- signif (sum (finfo$size) / 1024 / 1024, digits = 2)

    msg <- paste0 (
        "Data for the {corpus} corpus comprises {finfo_count} ",
        "file{?s} totalling around {finfo_size}MB."
    )
    cli::cli_alert_info (msg)

    if (!cli::has_keypress_support ()) {
        msg <- paste0 (
            "Your environment does not support key ",
            "entry, downloading will now proceed."
        )
        cli::cli_alert_warning (msg)
    } else {
        cli::cli_alert_info ("Do you want to proceed (y/n)?")
        k <- tolower (cli::keypress ())
        if (!k %in% c ("y", "n")) {
            cli::cli_abort ("Only 'y' or 'n' are recognised.")
        }
        if (k == "n") {
            cli::cli_abort ("Okay, stopping there")
        }
    }
}
